export const INIT_TEXTAREA_REF = 'INIT_TEXTAREA_REF';
export const MARKDOWN_TEXT_EDITOR_CHANGE = 'MARKDOWN_TEXT_EDITOR_CHANGE';
export const MARKDOWN_TEXT_SELECTION = 'MARKDOWN_TEXT_SELECTION';
export const SET_H1 = 'SET_H1';