export const MARKDOWN_TEXT_CONTENT_CHANGE = 'MARKDOWN_TEXT_CONTENT_CHANGE';

export const MARKDOWN_TEXT_SELECTION = 'MARKDOWN_TEXT_SELECTION';
export const TEXT_FORMATTING_APPLIED_H1 = 'TEXT_FORMATTING_APPLIED_H1';
export const TEXT_FORMATTING_APPLIED_H2 = 'TEXT_FORMATTING_APPLIED_H2';
export const TEXT_FORMATTING_APPLIED_H3 = 'TEXT_FORMATTING_APPLIED_H3';
export const TEXT_FORMATTING_APPLIED_BOLD = 'TEXT_FORMATTING_APPLIED_BOLD';
export const TEXT_FORMATTING_APPLIED_ITALIC = 'TEXT_FORMATTING_APPLIED_ITALIC';
export const TEXT_FORMATTING_APPLIED_STRIKETROUGH = 'TEXT_FORMATTING_APPLIED_STRIKETROUGH';
export const TEXT_FORMATTING_APPLIED_CODE = 'TEXT_FORMATTING_APPLIED_CODE';
export const TEXT_FORMATTING_APPLIED_BLOCKCODE = 'TEXT_FORMATTING_APPLIED_BLOCKCODE';
export const TEXT_FORMATTING_APPLIED_LINK = 'TEXT_FORMATTING_APPLIED_LINK';
export const TEXT_FORMATTING_APPLIED_LIST = 'TEXT_FORMATTING_APPLIED_LIST';
export const TEXT_FORMATTING_APPLIED_NUMBERS = 'TEXT_FORMATTING_APPLIED_NUMBERS';